package org.example.thought;

public enum ThinkingErrorTypes {
    CATASTROPHIZING,
    OVERGENERALIZATION,
    BLACK_AND_WHITE,
    MIND_READING,
    FORTUNE_TELLING,
    EMOTIONAL_REASONING,
    LABELING,
    PERSONALIZATION,
    SHOULD_STATEMENTS,
    DISCOUNTING_THE_POSITIVE,
    MENTAL_FILTERING,
    MAGNIFICATION_MINIMIZATION,
    NONE
}
